# Generated by Django 5.2 on 2025-05-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('DORMITORY_ADMIN', 'Dormitory Admin'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
    ]
