# Generated by Django 5.2 on 2025-05-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_room_photo_remove_room_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male')], default='male', max_length=20),
        ),
    ]
