# Generated by Django 5.2 on 2025-05-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_application_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='fio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='village',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='floor',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='university',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
