# Generated by Django 5.2 on 2025-05-24 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_student_course_remove_student_passport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('PARTIALLY_OCCUPIED', 'PARTIALLY_OCCUPIED'), ('FULLY_OCCUPIED', 'FULLY_OCCUPIED')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='floor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main.floor'),
        ),
        migrations.AlterField(
            model_name='student',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main.room'),
        ),
    ]
