# Generated by Django 5.2 on 2025-05-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_room_status_alter_student_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male')], default='male', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='discount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='student_pictures/'),
        ),
        migrations.AddField(
            model_name='student',
            name='social_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
