# Generated by Django 5.2 on 2025-05-25 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_room_gender_student_discount_student_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='accepted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='main.student'),
        ),
    ]
