# Generated by Django 5.2 on 2025-05-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_student_accepted_date_alter_payment_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paymentType',
            new_name='method',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='date',
            new_name='paid_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='room',
        ),
        migrations.AddField(
            model_name='payment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
