# Generated by Django 5.2 on 2025-05-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_paymenttype_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='student',
            name='social_status',
        ),
        migrations.AddField(
            model_name='student',
            name='imtiyoz',
            field=models.CharField(choices=[('0%', '0%'), ('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('80%', '80%'), ('90%', '90%'), ('100%', '100%')], default='0%', max_length=120),
        ),
        migrations.AddField(
            model_name='student',
            name='tarif',
            field=models.CharField(choices=[('Nogiron', 'Nogiron'), ("Boquvchisini yo'qotgan", "Boquvchisini yo'qotgan"), ('Yotoqxonada faol', 'Yotoqxonada faol'), ('Boshqa', 'Boshqa'), ('Oddiy', 'Oddiy')], default='Oddiy', max_length=120),
        ),
    ]
