# Generated by Django 5.2 on 2025-05-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_student_discount_remove_student_social_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
