# Generated by Django 5.2 on 2025-05-27 16:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='accepted_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
