# Generated by Django 5.2 on 2025-05-29 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_student_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dormitory',
            name='photo',
        ),
        migrations.AddField(
            model_name='dormitory',
            name='has_classroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dormitory',
            name='has_gym',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dormitory',
            name='has_library',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dormitory',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dormitory',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dormitory',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dormitory',
            name='month_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dormitory',
            name='year_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('3-Kishilik', '3-Kishilik'), ('5-Kishillik', '5-Kishillik')], default='3-Kishilik', max_length=20),
        ),
        migrations.CreateModel(
            name='DormitoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dormitory_images')),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dormitory')),
            ],
        ),
    ]
