# Generated by Django 5.2 on 2025-05-29 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_dormitory_photo_dormitory_has_classroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitoryimage',
            name='dormitory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.dormitory'),
        ),
    ]
