# Generated by Django 5.2 on 2025-05-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_dormitoryimage_dormitory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'APPROVED'), ('CANCELLED', 'CANCELLED')], max_length=20),
        ),
    ]
