# Generated by Django 5.2 on 2025-05-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='passport',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
