# Generated by Django 5.2 on 2025-06-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_student_group_student_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-06-11'),
            preserve_default=False,
        ),
    ]
