# Generated by Django 5.2 on 2025-07-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_application_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
    ]
