# Generated by Django 5.2 on 2025-07-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_room_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='tarif',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('1-kurs', '1-kurs'), ('2-kurs', '2-kurs'), ('3-kurs', '3-kurs'), ('4-kurs', '4-kurs'), ('5-kurs', '5-kurs')], default='1-kurs', max_length=120),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], default='Erkak', max_length=120),
        ),
        migrations.AlterField(
            model_name='student',
            name='imtiyoz',
            field=models.BooleanField(default=False),
        ),
    ]
