# Generated by Django 5.2 on 2025-07-08 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_student_tarif_student_course_student_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='imtiyoz',
            new_name='privilege',
        ),
        migrations.RemoveField(
            model_name='dormitory',
            name='has_classroom',
        ),
        migrations.RemoveField(
            model_name='dormitory',
            name='has_gym',
        ),
        migrations.RemoveField(
            model_name='dormitory',
            name='has_library',
        ),
        migrations.RemoveField(
            model_name='dormitory',
            name='has_wifi',
        ),
        migrations.AddField(
            model_name='dormitory',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Qarzdor', 'Qarzdor'), ('Haqdor', 'Haqdor')], default='Qarzdor', max_length=120),
        ),
        migrations.AddField(
            model_name='dormitory',
            name='amenities',
            field=models.ManyToManyField(related_name='amenities', to='main.amenity'),
        ),
    ]
