# Generated by Django 5.2 on 2025-07-16 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('admin', 'admin'), ('ijarachi', 'ijarachi')], max_length=20),
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('description_uz', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('exact_address', models.CharField(blank=True, max_length=255, null=True)),
                ('monthly_price', models.IntegerField(blank=True, null=True)),
                ('distance_to_university', models.IntegerField(blank=True, help_text='Universitetgacha masofa (km)', null=True)),
                ('room_type', models.CharField(choices=[('1 kishilik', '1 kishilik'), ('2 kishilik', '2 kishilik'), ('3 kishilik', '3 kishilik')], max_length=32)),
                ('gender', models.CharField(choices=[('Aralash', 'Aralash'), ('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=16)),
                ('total_rooms', models.PositiveIntegerField(default=1)),
                ('available_rooms', models.PositiveIntegerField(default=1)),
                ('rules_uz', models.JSONField(blank=True, default=list, help_text='O‘zbekcha qoidalar ro‘yxati', null=True)),
                ('rules_ru', models.JSONField(blank=True, default=list, help_text='Ruscha qoidalar ro‘yxati', null=True)),
                ('is_recommended', models.BooleanField(default=False, help_text='Tavsiya etilgan sifatida belgilash')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amenities', models.ManyToManyField(related_name='apartments', to='main.amenity')),
                ('nearby_university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='main.university')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='main.province')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='apartment_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.apartment')),
            ],
        ),
    ]
