# Generated by Django 5.2 on 2025-07-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_task_title_alter_user_role_apartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='accepted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
