# Generated by Django 5.2 on 2025-07-17 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_student_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='type',
            field=models.CharField(choices=[('service', 'Service')], default='service', max_length=120),
        ),
        migrations.AlterField(
            model_name='student',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main.room'),
        ),
    ]
