# Generated by Django 5.2 on 2025-07-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_amenity_type_alter_student_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitory',
            name='distance_to_university',
            field=models.IntegerField(blank=True, help_text='Universitetgacha masofa (km)', null=True),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='amenities',
            field=models.ManyToManyField(related_name='dormitories', to='main.amenity'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
