# Generated by Django 5.2 on 2025-07-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='distance_to_university',
            field=models.FloatField(blank=True, help_text='Universitetgacha masofa (km)', null=True),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='distance_to_university',
            field=models.FloatField(blank=True, help_text='Universitetgacha masofa (km)', null=True),
        ),
    ]
