# Generated by Django 5.2 on 2025-07-23 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_apartment_distance_to_university_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='placement_status',
            field=models.CharField(choices=[('Qabul qilindi', 'Qabul qilindi'), ('Joylashdi', 'Joylashdi')], default='Qabul qilindi', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main.floor'),
        ),
        migrations.AlterField(
            model_name='student',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main.room'),
        ),
    ]
