# Generated by Django 5.2 on 2025-07-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='room',
        ),
    ]
