# Generated by Django 5.2 on 2025-07-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_remove_application_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='passport',
        ),
        migrations.AddField(
            model_name='application',
            name='passport_image_first',
            field=models.ImageField(blank=True, null=True, upload_to='passport_image/'),
        ),
        migrations.AddField(
            model_name='application',
            name='passport_image_second',
            field=models.ImageField(blank=True, null=True, upload_to='passport_image/'),
        ),
    ]
