# Generated by Django 5.2 on 2025-07-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_answerforapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_pictures/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
