# Generated by Django 5.2 on 2025-07-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_application_user_image_alter_application_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='direction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
