# Generated by Django 5.2 on 2025-07-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_application_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='type',
        ),
    ]
