# Generated by Django 5.2 on 2025-07-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_remove_amenity_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='description_ru',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='title_ru',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='distance_to_university',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='is_recommended',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='nearby_university',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='rules_ru',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='rules_uz',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='title_uz',
        ),
        migrations.AddField(
            model_name='apartment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='gender',
            field=models.CharField(choices=[('Aralash', 'Aralash'), ('Erkak', 'Erkak'), ('Ayol', 'Ayol')], default='Erkak', max_length=16),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='room_type',
            field=models.CharField(choices=[('1 kishilik', '1 kishilik'), ('2 kishilik', '2 kishilik'), ('3 kishilik', '3 kishilik'), ('Oilaviy', 'Oilaviy')], default='Oilaviy', max_length=32),
        ),
    ]
