# Generated by Django 5.2 on 2025-07-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_application_admin_comment_alter_student_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passport_image_first',
            field=models.ImageField(blank=True, null=True, upload_to='passport_image/'),
        ),
        migrations.AddField(
            model_name='student',
            name='passport_image_second',
            field=models.ImageField(blank=True, null=True, upload_to='passport_image/'),
        ),
    ]
