# Generated by Django 5.2 on 2025-07-27 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_notificationadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationadmin',
            name='title',
        ),
    ]
