# Generated by Django 5.2 on 2025-07-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_remove_notificationadmin_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Qarzdor', 'Qarzdor'), ('Haqdor', 'Haqdor'), ('Tekshirilmaydi', 'Tekshirilmaydi')], default='Tekshirilmaydi', max_length=120),
        ),
    ]
