# Generated by Django 5.2 on 2025-08-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_alter_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationadmin',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
