# Generated by Django 5.2 on 2025-08-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_notificationadmin_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='privilege_share',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
