# Generated by Django 5.2 on 2025-08-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_student_privilege_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
