# Generated by Django 5.2 on 2025-08-16 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_dormitory_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bildirishnoma', 'verbose_name_plural': 'Bildirishnomalar'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.ImageField(blank=True, help_text='Bildirishnoma rasmi', null=True, upload_to='notifications/'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Bildirishnoma faolmi'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_type',
            field=models.CharField(choices=[('all_students', 'Barcha studentlar'), ('all_admins', 'Barcha adminlar'), ('specific_user', "Ma'lum foydalanuvchi")], default='all_students', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_user',
            field=models.ForeignKey(blank=True, help_text='Agar specific_user tanlansa, bu foydalanuvchi', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(help_text='Bildirishnoma matni'),
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='main.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
                'unique_together': {('user', 'notification')},
            },
        ),
        migrations.DeleteModel(
            name='NotificationAdmin',
        ),
    ]
