# Generated by Django 5.2 on 2025-08-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target_type',
            field=models.CharField(choices=[('all_students', 'Barcha studentlar'), ('all_admins', 'Barcha adminlar'), ('specific_user', "Ma'lum foydalanuvchi")], default='specific_user', max_length=20),
        ),
    ]
