# Generated by Django 5.2 on 2025-08-19 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_alter_notification_target_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='created_by',
        ),
    ]
