# Generated by Django 5.2 on 2025-08-20 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_remove_notification_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='city',
            new_name='faculty',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='fio',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='village',
            new_name='middle_name',
        ),
        migrations.AddField(
            model_name='application',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.district'),
        ),
        migrations.AddField(
            model_name='application',
            name='group',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='passport',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='application',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.province'),
        ),
    ]
