# Generated by Django 5.2 on 2025-08-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_applicationnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='university',
        ),
        migrations.AddField(
            model_name='application',
            name='course',
            field=models.CharField(choices=[('1-kurs', '1-kurs'), ('2-kurs', '2-kurs'), ('3-kurs', '3-kurs'), ('4-kurs', '4-kurs'), ('5-kurs', '5-kurs')], default='1-kurs', max_length=120),
        ),
    ]
