# Generated by Django 5.2 on 2025-08-24 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
    ]
