# Generated by Django 5.2 on 2025-08-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_alter_notification_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
