# Generated by Django 5.2 on 2025-09-09 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FloorLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='main.floor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_leaderships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('floor', 'user')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='main.floor')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='main.floorleader')),
            ],
            options={
                'unique_together': {('date', 'floor')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Hozir', 'Hozir'), ('Kech', 'Kech'), ('Yo‘q', 'Yo‘q')], default='Hozir', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='main.student')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='main.attendancesession')),
            ],
            options={
                'unique_together': {('session', 'student')},
            },
        ),
        migrations.CreateModel(
            name='CollectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('To‘lagan', 'To‘lagan'), ('To‘lamagan', 'To‘lamagan')], max_length=30)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='main.collection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_records', to='main.student')),
            ],
            options={
                'unique_together': {('collection', 'student')},
            },
        ),
    ]
