# Generated by Django 5.2 on 2025-09-09 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_collection_floorleader_attendancesession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='main.floor'),
        ),
        migrations.AddField(
            model_name='collection',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='main.floorleader'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('admin', 'admin'), ('ijarachi', 'ijarachi'), ('floor_leader', 'floor_leader')], max_length=20),
        ),
    ]
