# Generated by Django 5.2 on 2025-09-10 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_collection_floor_collection_leader_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorleader',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='main.floor'),
        ),
        migrations.AlterField(
            model_name='floorleader',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='floor_leader', to=settings.AUTH_USER_MODEL),
        ),
    ]
