# Generated by Django 5.2 on 2025-09-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_alter_floorleader_floor_alter_floorleader_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('Bor', 'Bor'), ('Kech', 'Kech'), ('Yo‘q', 'Yo‘q')], default='Bor', max_length=20),
        ),
    ]
