# Generated by Django 5.2 on 2025-09-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_alter_attendancerecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('in', 'in'), ('out', 'out')], default='in', max_length=20),
        ),
    ]
