# Generated by Django 5.2 on 2025-09-20 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_dutyschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitory',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dormitory', to=settings.AUTH_USER_MODEL),
        ),
    ]
