# Generated by Django 5.2 on 2025-09-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_alter_dormitory_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
