# Generated by Django 5.2 on 2025-05-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='gender_type',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='female', max_length=20, verbose_name='Gender type'),
        ),
    ]
