# Generated by Django 5.2 on 2025-05-08 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0002_alter_floor_gender_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type_category',
        ),
    ]
